#!/usr/bin/env python

import subprocess

logo = r"""
 ____             _              _                  ___  ____  
|  _ \ ___  _ __ | |_ __ ___  _(_)_   _ _ __ ___   / _ \/ ___| 
| |_) / _ \| '_ \| __/ _` \ \/ / | | | | '_ ` _ \ | | | \___ \ 
|  __/  __/| | | | || (_| |>  <| | |_| | | | | | || |_| |___) |
|_|   \___||_| |_|\__\__,_/_/\_\_|\__,_|_| |_| |_| \___/|____/ 
"""

def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True).strip()
    except Exception:
        return "Unknown"

def sysFetch():
    user = run_cmd("whoami")
    host = run_cmd("echo $HOSTNAME")
    user_host = f"  {user}@{host}"
    
    os_name = run_cmd("grep '^NAME=' /etc/os-release | cut -d'=' -f2 | tr -d '\"'")
    kernel = run_cmd("uname -r")
    
    user_theme = run_cmd("gsettings get org.gnome.desktop.interface gtk-theme | tr -d \"'\"")
    icon_theme = run_cmd("gsettings get org.gnome.desktop.interface icon-theme | tr -d \"'\"")
    cursor_theme = run_cmd("gsettings get org.gnome.desktop.interface cursor-theme | tr -d \"'\"")
    font = run_cmd("gsettings get org.gnome.desktop.interface font-name | tr -d \"'\"")
    term_font = run_cmd("gsettings get org.gnome.desktop.interface monospace-font-name | tr -d \"'\"")

    if os_name == "Unknown": os_name = "PentaxiumOS"
    
    info = [
        f"{user_host}",
        "-" * (len(user_host) - 2),
        f"󰋜  OS:            {os_name}",
        f"  Kernel:        {kernel}",
        f"󰃟  User theme:    {user_theme}",
        f"󰀻  Icon theme:    {icon_theme}",
        f"󰇀  Cursor theme:  {cursor_theme}",
        f"󰗚  Font:          {font}",
        f"  Terminal font: {term_font}"
    ]
    
    max_len = max(len(line) for line in info)
    
    print(logo)
    print("┌" + "─" * (max_len + 4) + "┐")
    for line in info:
        if line == "-" * (len(user_host) - 2):
            print("├" + "─" * (max_len + 4) + "┤")
        else:
            print(f"│  {line.ljust(max_len)}  │")
    print("└" + "─" * (max_len + 4) + "┘")

if __name__ == "__main__":
    sysFetch()
